version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    volumes:
    - ./init_01_create_user.sh:/docker-entrypoint-initdb.d/init_01_create_user.sh
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DJANGO_POSTGRES_USER
      - DJANGO_POSTGRES_PASSWORD
    ports:
      - 5432:5432
    restart: always
  api:
    build:
      context: ./comments_for_strategia
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - ./comments_for_strategia:/comments-api
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=db
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - SECRET_KEY
      - DJANGO_POSTGRES_USER
      - DJANGO_POSTGRES_PASSWORD
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8080"
    restart: always
